### ISSUE TITLE
Kanban board submission

### ISSUE THREAD

**Issue by edi-sipka** [edi-sipka/Recipe_app#13]
Our team is consists of 3 members, and we are:

- Edi Šipka
- Moathal Kachi
- Riya Bulia 

Our Kanban board is: https://github.com/users/edi-sipka/projects/2

**Comment by sja-thedude** [comment]
## Required Changes ♻️

Hi @edi-sipka, @RiyaBulia12 & @Moathal, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ Good job assigning the members correctly for tasks
✔️ Correct Kanban Board setup

## Required 
- [ ] Kindly make sure that for the Initial Project setup you add the description that I have pointed out in the video attached where "No description provided" is written.

https://user-images.githubusercontent.com/70269507/208442186-71685eb7-b579-4d43-a1fd-ffc5afac9171.mov

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by edi-sipka** [comment]
Hi @sja-thedude thank you for this.
I fixed it :)

**Comment by sja-thedude** [comment]
## Project Approved 👍 

Hi @edi-sipka, @RiyaBulia12 & @Moathal, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to start working on the project it :shipit: 
Congratulations! 🎉 

# Highlights:
- Correct kanban setup
- All requirements completed

![giphy](https://user-images.githubusercontent.com/70269507/159485323-11dfc0c5-bd53-4956-b55a-2fc42f7a3845.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
